name: antiquities_e_commerce
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  json_serializable: ^6.6.2
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Heavy.otf
        - asset: assets/fonts/Avenir-Regular.otf
        - asset: assets/fonts/Avenir-Book.otf
